name: Build Word Search Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools: '35.0.0-rc1'

    - name: Accept Android Licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Build and Deploy Kivy App
      run: |
        buildozer android debug deploy run
