name: Build Word Search Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build Kivy App
      run: |
        buildozer init
        buildozer android debug deploy run

    # If you want to run the built package
    # - name: Run Kivy App
    #   run: |
    #     # Commands to run the built package
